Linear Algebra
==

Lesson notes from https://youtu.be/9YtmGy-wfE4


Cheat Sheet
--
$Av=λv$ $A$ is a Transitional matrix that scales vector in $v$ space by $λ$  
$λ$ is called the eigen value and $v$ the corresponding eigen vector for transitional matrix A  
$|A-λI|$ can used to evaluate eigen values for a given transitional matrix A. And thus also the corresponding eigen vectors.  
**Eigen Value Decomposition**  
If matrix $A$ is symmetrical then  
* all $λ$ would be real.
* $A=UDU^T$  
Where is D is a diagonal matrix with eigen values in the diagonal and U is has the eigen vectors in the corresponding columns, this is called Diagonalisation of a matrix.  

**Single Value Decomposition**  
For any non-symmetrical matrix $A_m*n$  
$A_{m*n}=U_{m*m}\sum_{m*n}V_{n*n}^T$  
Simplified as for a matrix $A_{m*n}$ where $m<n$     
$A_{m*n}=U_{m*m}\sum_{m*m}V_{n*m}^T$   
Given solution for $A^TA=V_sDV_s^{-1}$  
From $V_s$ can be discard the vectors $i>m$ till $i=n$ and get $A$'s $V$  
From $D$ get $\sum$ by taking squareroot of all the positive λs (call it $\sigma$)and taking largest $m$ of $n$.  
Now get $U$ by $u_i=\frac{Av_i}{\sigma_i}$  
**Importantly we need to make sure that $U$ and $V$ are normalized to vector length of 1***  


$\qquad\gamma _{A}(\lambda )=n-\operatorname {rank} (A-\lambda I).$

Eigen Values and Eigen Vectors
--
If $A$ is $n*n$ Matrix then there exists a eigen value(complex) $\lambda$ and eigen vector $v$ such that  
    
<div style="border:solid">$\quad Av=\lambda v$</div>

$\quad Av-\lambda v=0$

$\quad (A-\lambda I)v=0$
<div style="border:solid">$\quad |A-\lambda I|=0\quad \quad$</div>
--
<pre>for non zero eigen vector v to exist </pre>

##### Getting Eigen Values
If we consider $\lambda$ to be a variable then $|A-\lambda I|=0$ becomes a characteristic polynomial equation of the order of matrix $A$ ($n$). Called **characteristic polynomial** of $A$.  
$(\lambda - \lambda_{1})(\lambda - \lambda_{2})(\lambda - \lambda_{3})...(\lambda - \lambda_{i})...(\lambda - \lambda_{n})=0$  
(If you are confused about how a matrix representation became an polynomial equation in $\lambda$ see the example workout below)  
Now $\lambda_{1},\lambda_{2}...\lambda_{n}$ are eigen values of matrix $A$
##### Getting Eigen Vectors
After this we can get the corresponding eigen vectors $v_{1},v_{2}...v_{n}$.

Geometrically speaking  
$A$ scales $v_{1}\quad by\quad\lambda_{1}$  
$A$ scales $v_{4}\quad by\quad\lambda_{2}$  
.  
.  
.  
$A$ scales $v_{n}\quad by\quad\lambda_{n}$  


##### Properties of Eigen Values and Eigen Vectors #####


###### Algebraic and Geometric Multiplicity ######
In the above polynomial equation in $\lambda$, there could be duplicate solutions when  
$(\lambda - \lambda_{1})^{g_{1}}(\lambda - \lambda_{2})^{g_{2}}(\lambda - \lambda_{3})^{g_{3}}...(\lambda - \lambda_{i})^{g_{i}}=0$  
$\sum_{j=1}^{i} g_{j}=n\quad$ Where $g_{j}$ is the **algebraic multiplicity** of $\lambda_{j}$ w.r.t the polynomial equation all arrived at from the transformation matrix $A$.  
$g_{j}$ the algebraic multiplicty is usually denoted as $\mu_{A}(\lambda_{j})$.

For each eigen value $\lambda$ there could be multiple *linearly independent* eigen vectors if $\mu_{A}(\lambda)>1$.  
The number of linearly independent eignen vectors for each eigen value is known as **geometric multiplicity** denoted by $\gamma_A(\lambda)$.  
$1\leq\gamma_A(\lambda)\leq\mu_A(\lambda)\leq n\quad$ for a given Matrix $A$ of size $n*n$ and one of its eigen value $\lambda$   

<div style="border:groove">$\lambda$ could be a complex number</div>
--
$\lambda$ is called a simple eigenvalue if it's algebraic mulitplicity is one.  
$\lambda$ is called a semisimple eigenvalue if $\mu_A(\lambda)=\gamma_A(\lambda)$  


#### For any Matrix $A$ with complex numbers  

$\operatorname {tr} (A)=\sum _{i=1}^{n}A_{ii}=\sum _{i=1}^{n}\lambda _{i}=\lambda _{1}+\lambda _{2}+\cdots +\lambda _{n}.$  

$\det(A)=\prod _{i=1}^{n}\lambda _{i}=\lambda _{1}\lambda _{2}\cdots \lambda _{n}.$  

#### Special Cases where handling of Matrices becomes easier.  

Conjugate of a complex number $c=x+iy$ is $\bar{c}=x-iy$.  
Conjugate of a matrix $A$ is denoted as $\bar{A}$.  
$\quad$Where $A_{i,j}=conjugate((\bar{A})_{j,i})$.      
$A$ is Hermitian matrix if $A=\bar{A}^T$.  
Conjugate Transpose of $A$, $\bar{A}^T$ is usually denoted as $A^*$.  
In case of $A=A^*$, all eigen values would be real.  
When $A$ is real, $A=\bar{A}$.  
When $A$ is symmetric, $A=A^T$.  
When $A$ is real symmetric all it's eigen values would be real.  

When $A$ is Hermitan $A=A^*$ which is $\bar{A^T}$  
$\quad\bar{v^T}Av = \bar{v^T} · (λv) = λ ||v||^2\qquad(i)$  
$\quad\bar{v^T}Av = \bar{v^T}\bar{A^T} · v\qquad Given-A-is-Hermitan$  
$\qquad\implies\bar{v^T}Av = \bar{(Av)^T} · v$  
$\qquad\implies\bar{v^T}Av = \bar{(λv)^T} · v$  
$\qquad\implies\bar{v^T}Av = \bar{(λv)^T} · v$  
$\qquad\implies\bar{v^T}Av = \bar{(λv)^T} · v$  
$\qquad\implies\bar{v^T}Av = \bar{λ}\bar{v^T} · v$  
$\qquad\implies\bar{v^T}Av = \bar{λ}||v||^2$  
$\qquad\implies\bar{v^T}Av = \bar{λ}||v||^2 = λ ||v||^2\qquad from (i)$
<div style="border:groove">$\qquad\bar{λ}=λ\qquad$ Thus λ is real, when $A=A^*=\bar{A^T}$, esp. when $A$ is real symmetric</div>  
<div style="border:solid">When $A$ is real symmetric all it's eigen values would be real.</div>
--

You can go to https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors for further information.



### Diagnolisable

$\quad Av=\lambda v$  
$\qquad \implies A{\begin{bmatrix} v_1 &v_2 &\cdots &v_n \end{bmatrix}} ={\begin{bmatrix}\lambda _{1}v_{1}&\lambda _{2}v_{2}&\cdots &\lambda _{n}v_{n}\end{bmatrix}}$.  
$\qquad if D = \left[{\begin{array}{cccc} \lambda_1&0&\cdots &0\\ 0&\lambda_2&\cdots &0\\\vdots \\0&0&\cdots &\lambda_n \end{array}}\right]$  
$\qquad if U={\begin{bmatrix} v_1 &v_2 &\cdots &v_n \end{bmatrix}}$  
$\qquad\implies AU=UD$  
$\qquad\implies A=UDU^{-1}$  

Conversly if we can decompose $A$ in to $UDU^{-1}$ where $D$ is a diagonal matrix. Then the diagonal elements of $D$ would be the eigen values and the columns in $U$ would be eigen vectors.


### Singular Value Decomposition

Eigen Value decomposition is useful for symmetric matrices for non symmetric matrices we can use SVD.

$\quad A_{m*n}=U_{m*m}\sum_{m*n}V_{n*m}^{T}$  
Here $A$ is called transformation matrix from $m$ space to $n$ space.  
$U$ and $V$ should be orthogonal matrices and $\sum$ should be a diagonal matrix.

Given solution for $A^TA=V_sDV_s^{-1}$  
From $V_s$ can be discard the vectors $i>m$ till $i=n$ and get $A$'s $V$  
From $D$ get $\sum$ by taking squareroot of all the positive λs (call it $\sigma$)and taking largest $m$ of $n$.  
#### <div style="border:solid"> Now get $U$ by $u_i=\frac{Av_i}{\sigma_i}$</div>  
**Importantly we need to make sure that $U$ and $V$ are normalized to vector length of 1***  


## Examples
*****
*****
### Example of how to get eigen values and their respective Eigen Vectors ######

$\quad A=\left[{\begin{array}{cc} 2&1\\1&2 \end{array}}\right]$

$\quad A-\lambda I = \left[{\begin{array}{cc} 2-\lambda &1\\1&2-\lambda \end{array}}\right]$

$\quad |A-\lambda I|=0$

$\quad =>(2-\lambda)*(2-\lambda)-1*1=0$

$\quad =>3-4\lambda +\lambda ^2=0$

$\quad =>(\lambda -3)*(\lambda -1)=0$

$\quad => \lambda =3$

    OR

$\quad \quad  \lambda =1$

So here 3 and 1 are *eigen values*. Once we've the eigen values we could get the corresponding *eigen vectors*

$\quad Av=\lambda v$

###### For $\lambda =1$
$\quad Av=1*v\quad    For\quad    \lambda =1$
    
$ \left[{\begin{array}{cc} 2&1\\1&2 \end{array}}\right] * \left[{\begin{array}{c} x\\y \end{array}}\right] = \left[{\begin{array}{c} x\\y \end{array}}\right]$

Both equations give $x=-y$
So $v_{\lambda =1}=\left[{\begin{array}{c} 1\\-1 \end{array}}\right]$ or any non-zero scalar multiple of the same.

###### For $\lambda =3$
$\quad Av=3*v\quad    For\quad    \lambda =3$
    
$ \left[{\begin{array}{cc} 2&1\\1&2 \end{array}}\right] * \left[{\begin{array}{c} x\\y \end{array}}\right] = \left[{\begin{array}{c} 3x\\3y \end{array}}\right]$

Both equations give $x=y$
So $v_{\lambda =1}=\left[{\begin{array}{c} 1\\1 \end{array}}\right]$ or any non-zero scalar multiple of the same.

###### So for A, eigen values are 1 and 3 and their corresponding eigen vectors are $v_{\lambda =1}=\left[{\begin{array}{c} 1\\-1 \end{array}}\right]$ and $v_{\lambda =1}=\left[{\begin{array}{c} 1\\1 \end{array}}\right]$
*******
*******
### Another Example of decomposition for a diagonal matrix

$\quad A=\left[{\begin{array}{ccc} 1&0&0\\0&2&0\\0&0&3 \end{array}}\right]$  
Now do $|A-\lambda I|=0$  
$\quad(1-\lambda)*(2-\lambda)*(3-\lambda)=0$  
$\quad\lambda_1=1,\lambda_2=2,\lambda_3=3$  
For $v_1 (\lambda_1=1)$  
$\quad x=x$  
$\quad\quad$True for any x, so we choose x=1 and all it's non zero scalar multiples as eigen vectors  
$\quad2y=y$  
$\quad\quad$y=0  
$\quad3z=z$  
$\quad\quad$z=0  
$\quad v_1=\left[{\begin{array}{c} 1\\0\\0 \end{array}}\right]$  
For $v_2 (\lambda_2=2)$  
$\quad x=2x$  
$\quad 2y=2y$  
$\quad 3z=2z$  
$\quad v_1=\left[{\begin{array}{c} 0\\1\\0 \end{array}}\right]$  
For $v_3 (\lambda_3=3)$  
$\quad x=3x$  
$\quad 2y=3y$  
$\quad 3z=3z$  
$\quad v_1=\left[{\begin{array}{c} 0\\0\\1 \end{array}}\right]$  

****
****


### SVD Example

$\quad A= \left[{\begin{array}{ccc} 3&2&2\\2&3&-2 \end{array}}\right]$  
$\quad A^TA = \left[{\begin{array}{cc} 3&2\\2&3\\2&-2 \end{array}}\right].\left[{\begin{array}{ccc} 3&2&2\\2&3&-2 \end{array}}\right]$  
$\quad A^TA=\left[{\begin{array}{ccc} 13&12&2\\12&13&-2\\2&-2&8 \end{array}}\right]$  
$\quad |A^TA-\lambda I|=0$  
$\quad\implies \left|\left[{\begin{array}{ccc} 13-λ&12&2\\12&13-λ&-2\\2&-2&8-λ \end{array}}\right]\right|=0$  
$\quad\implies (13-λ)((13-λ)*(8-λ)-4)-12(96-12λ+4)+2(-24-26+2λ)=0$  
$\quad\implies (13-λ)(13*8-13λ-8λ+λ^2-4)-12^2*2^3+12^2λ-12*2^2-12*4-13*4+4λ=0$  
$\quad\implies (13-λ)(2^2*5^2+(2^2-5^2)λ+λ^2)-13*2^2*5^2+4λ+12^2λ=0$  
$\quad\implies (13-λ)(2^2*5^2+(2^2-5^2)λ+λ^2)-13*2^2*5^2+4λ+12^2λ=0$  
$\quad\implies 13(2^2*5^2+(2^2-5^2)λ+λ^2)-λ(2^2*5^2+(2^2-5^2)λ+λ^2)+148λ-13*2^2*5^2=0$  
$\quad\implies 13*2^2*5^2+13(2^2-5^2)λ+13λ^2-2^2*5^2λ-(2^2-5^2)λ^2-λ^3+148λ-13*2^2*5^2=0$  
$\quad\implies -λ^3+13λ^2-(2^2-5^2)λ^2+13(2^2-5^2)λ-2^2*5^2λ+148λ+13*2^2*5^2-13*2^2*5^2=0$  
$\quad\implies -λ^3+13λ^2-(2^2-5^2)λ^2+13(2^2-5^2)λ-2^2*5^2λ+148λ=0$  
$\quad\implies -λ^3+(13+5^2-2^2)λ^2-13(5^2-2^2)λ-2^2*5^2λ+148λ=0$  
$\quad\implies -λ^3+(13+5^2-2^2)λ^2-(13*5^2-13*2^2+2^2*5^2)λ+148λ=0$  
$\quad\implies -λ^3+34λ^2-373λ+148λ=0$  
$\quad\implies -λ^3+34λ^2-225λ=0$  
$\quad\implies -λ(λ^2-(25+9)λ+25*9)=0$  
$\quad\implies -λ(λ-25)(λ-9)=0$  
$\quad\implies λ=25,9,0$  
$D = \left[{\begin{array}{ccc} 25&0&0\\0&9&0\\0&0&0 \end{array}}\right]$  this is $D$ for $A^TA$  
This also gives us the below:-  
$\sum=\left[{\begin{array}{ccc} 5&0&0\\0&3&0\\0&0&0 \end{array}}\right]$  this is $\sum$ in " $A=U\sum V^T$  "
--


Let's calculate the eigenvectors for $A^TA$  
$\quad A^TAv_1=λ_1v_1$  
$\left[{\begin{array}{ccc} 13&12&2\\12&13&-2\\2&-2&8 \end{array}}\right]\left[{\begin{array}{c} x\\y\\z \end{array}}\right]=\left[{\begin{array}{c} 25x\\25y\\25z \end{array}}\right]$  


    
$13x+12y+2z=25x$  
$12x+13y-2z=25y$  
$2x-2y+8z=25z$  
  
$x-y=z/6$  
$x-y=17z/2$  
  
$x=1,y=1,z=0$ and any non zero scalar multiple of the same would be an eigen vector for $\lambda=25$  
$\quad v_{\lambda = 25}=\left[{\begin{array}{c}1\\1\\0\end{array}}\right]$  
  
$13x+12y+2z=9x$  
$12x+13y-2z=9y$  
$2x-2y+8z=9z$  
  
$2x+6y=-z$
$6x+2y=z$
$2x-2y=z$
  
$\quad v_{\lambda = 9}=\left[{\begin{array}{c}1\\-1\\4\end{array}}\right]$
  
There is really no need for us to calculate the eigenvector when $λ=0$  
$13x+12y+2z=0  
$12x+13y-2z=0  
$2x-2y+8z=0  
  
$x=-y$
$x=-2z$
  
$\quad v_{\lambda = 9}=\left[{\begin{array}{c}1\\-1\\-1/2\end{array}}\right]$


Now $V=\left[{\begin{array}{ccc}1&1&1\\1&-1&-1\\0&4&-1/2\end{array}}\right]$  this is $V$ in " $A=U\sum{}V^T$  "
Now $V=\left[{\begin{array}{ccc}1/\sqrt{2}&1/\sqrt{18}&1\\1/\sqrt{2}&-1/\sqrt{18}&-1\\0&4/\sqrt{18}&-1/2\end{array}}\right]$  this is $V$ in " $A=U\sum{}V^T$  "
--

<div style="border:solid">From SVD we define $u_i=Av_i/\sigma_i$  </div>
--  
$u_1=1/\sigma_1 \left[{\begin{array}{ccc} 3&2&2\\2&3&-2 \end{array}}\right].\left[{\begin{array}{c}1\\1\\0\end{array}}\right]$  
$u_i=1/5 \left[{\begin{array}{c} 5\\5 \end{array}}\right]$  
$u_i=\left[{\begin{array}{c} 1\\1 \end{array}}\right]$  
  
$u_2=1/\sigma_2 \left[{\begin{array}{ccc} 3&2&2\\2&3&-2 \end{array}}\right].\left[{\begin{array}{c}1\\-1\\4\end{array}}\right]$  
$u_i=1/3 \left[{\begin{array}{c} 9\\-9 \end{array}}\right]$  
$u_i=\left[{\begin{array}{c} 3\\-3 \end{array}}\right]$  

Now $U=\left[{\begin{array}{cc}1&3\\1&-3\end{array}}\right]$  this is $V$ in " $A=U\sum{}V^T$  "  
Now $U=\left[{\begin{array}{cc}1/\sqrt{2}&1/\sqrt{2}\\1/\sqrt{2}&-1/\sqrt{2}\end{array}}\right]$  this is $V$ in " $A=U\sum{}V^T$  "
--

Now let's calculate $U\sum V^T$  
$U\sum V^T=\left[{\begin{array}{cc}1&3\\1&-3\end{array}}\right].\left[{\begin{array}{ccc} 5&0&0\\0&3&0\\0&0&0 \end{array}}\right].\left[{\begin{array}{ccc}1&1&1\\1&-1&-1\\0&4&-1/2\end{array}}\right]^T$  


In [21]:
import numpy as np
U=[[1,3],[1,-3]]
D=[[5,0],[0,3]]
V=np.asarray([[1,1],[1,-1],[0,4]])
A=np.matmul(U,D)
A=np.matmul(A,np.matrix.transpose(V))
print(A)

[[ 14  -4  36]
 [ -4  14 -36]]


$U\sum V^T=\left[{\begin{array}{cc}1&3\\1&-3\end{array}}\right].\left[{\begin{array}{ccc} 5&0\\0&3 \end{array}}\right].\left[{\begin{array}{ccc}1&1&1\\1&-1&-1\\0&4&-1/2\end{array}}\right]^T$  
$U\sum V^T=\left[{\begin{array}{cc}1&3\\1&-3\end{array}}\right].\left[{\begin{array}{ccc} 5&0\\0&3 \end{array}}\right].\left[{\begin{array}{cc} 1&1\\1&-1\\0&4\end{array}}\right]^T$  
$U\sum V^T=\left[{\begin{array}{cc}1&3\\1&-3\end{array}}\right].\left[{\begin{array}{ccc} 5&0\\0&3 \end{array}}\right].\left[{\begin{array}{ccc} 1&1&0\\1&-1&4 \end{array}}\right]$  
$U\sum V^T=\left[{\begin{array}{cc}5&9\\5&-9\end{array}}\right].\left[{\begin{array}{ccc} 1&1&0\\1&-1&4 \end{array}}\right]$  

Well clearly this is not working... So we need to make sure that the eigen vectors are unary.

$U\sum V^T=$$\left[{\begin{array}{cc}1/\sqrt{2}&1/\sqrt{2}\\1/\sqrt{2}&-1/\sqrt{2}\end{array}}\right]$.$\left[{\begin{array}{ccc} 5&0&0\\0&3&0\\0&0&0 \end{array}}\right].\left[{\begin{array}{ccc}1/\sqrt{2}&1/\sqrt{18}&1\\1/\sqrt{2}&-1/\sqrt{18}&-1\\0&4/\sqrt{18}&-1/2\end{array}}\right]^T$  



In [20]:
import numpy as np
U=[[1/2**0.5,1/2**0.5],[1/2**0.5,-1/2**0.5]]
D=[[5,0],[0,3]]
V=np.asarray([[1/2**0.5,1/18**0.5],[1/2**0.5,-1/18**0.5],[0,4/18**0.5]])
A=np.matmul(U,D)
A=np.matmul(A,np.matrix.transpose(V))
print(A)


[[ 3.  2.  2.]
 [ 2.  3. -2.]]


$U\sum V^T=\left[{\begin{array}{cc}1/\sqrt{2}&1/\sqrt{2}\\1/\sqrt{2}&-1/\sqrt{2}\end{array}}\right].\left[{\begin{array}{ccc} 5&0\\0&3 \end{array}}\right].\left[{\begin{array}{ccc}1/\sqrt{2}&1/\sqrt{18}&1\\1/\sqrt{2}&-1/\sqrt{18}&-1\\0&4/\sqrt{18}&-1/2\end{array}}\right]^T$  
$U\sum V^T=\left[{\begin{array}{cc}1/\sqrt{2}&1/\sqrt{2}\\1/\sqrt{2}&-1/\sqrt{2}\end{array}}\right].\left[{\begin{array}{ccc} 5&0\\0&3 \end{array}}\right].\left[{\begin{array}{cc} 1/\sqrt{2}&1/\sqrt{18}\\1/\sqrt{2}&-1/\sqrt{18}\\0&4/\sqrt{18}\end{array}}\right]^T$  
$U\sum V^T=\left[{\begin{array}{cc}1/\sqrt{2}&1/\sqrt{2}\\1/\sqrt{2}&-1/\sqrt{2}\end{array}}\right].\left[{\begin{array}{ccc} 5&0\\0&3 \end{array}}\right].\left[{\begin{array}{ccc} 1/\sqrt{2}&1/\sqrt{2}&0\\1/\sqrt{18}&-1/\sqrt{18}&4/\sqrt{18} \end{array}}\right]$  
$U\sum V^T=\left[{\begin{array}{cc}1/\sqrt{2}&1/\sqrt{2}\\1/\sqrt{2}&-1/\sqrt{2}\end{array}}\right].\left[{\begin{array}{ccc} 5&0\\0&3 \end{array}}\right].\left[{\begin{array}{ccc} 1/\sqrt{2}&1/\sqrt{2}&0\\1/\sqrt{18}&-1/\sqrt{18}&4/\sqrt{18} \end{array}}\right]$  
$U\sum V^T=\left[{\begin{array}{cc}5/\sqrt{2}&3/\sqrt{2}\\5/\sqrt{2}&-3/\sqrt{2}\end{array}}\right].\left[{\begin{array}{ccc} 1/\sqrt{2}&1/\sqrt{2}&0\\1/\sqrt{18}&-1/\sqrt{18}&4/\sqrt{18} \end{array}}\right]$  
$U\sum V^T=\left[{\begin{array}{ccc} 6/\sqrt{2}^2&4/\sqrt{2}^2&\frac{3*4}{3*2}\\5/\sqrt{2}^2&6/\sqrt{2}^2&-\frac{3*4}{3*2} \end{array}}\right]$  
$U\sum V^T=\left[{\begin{array}{ccc} 3&2&2\\2&3&-2 \end{array}}\right]=A$  





##### Single Value Decomposition


##### Known notes
Given

$a_{1}x + b_{1}y + c_{1}z =k_{1}$

$a_{2}x + b_{2}y + c_{2}z =k_{2}$

$a_{3}x + b_{3}y + c_{3}z =k_{3}$

$A=\left[{\begin{array}{ccc} 
    a_{1} & b_{1} & c_{1}\\
    a_{2} & b_{2} & c_{2}\\
    a_{3} & b_{3} & c_{3}\\
    \end{array}} \right]$

and

$K=\left[{\begin{array}{c} 
    k_{1}\\
    k_{2}\\
    k_{3}\\
    \end{array}} \right]$


$V=\left[{\begin{array}{c} 
    x\\
    y\\
    z\\
    \end{array}} \right]$

$AV=K$

$=>A^{-1}AV=A^{-1}K$

$=>IV=A^{-1}K$

$=>V=A^{-1}K$

$=>V=\frac{1}{|A|} adj(A)K$

$=>V=\frac{1}{|A|} C^{T}K$

Where **C** is a co-factor matrix of **A**

To support an earlier version when

$AV-K=0$

$(A-KI)V=0 ??$




### Unknown Terms that should be learnt

*  Lebesgue Measure
*  Gram Schmidt Process

###### Useful is SVD
*  Cholesky Decomposition (LU etc..)
*  QR Algorithm


### Assignment Problems

###### Problem A-1. 
Decide whether the following statements are true or false. No explanation
needed.  
  
1. The row-rank and column-rank of a matrix is always equal to each other.  
$\quad$ True  
  
2. For a $m × n$ matrix $A$ and a $n × g$ matrix $B$, it is always true that rank(AB) ≤ rank(A).  
$\quad$ True in fact rank(AB) ≤ min(rank(A),rank(B))  
  
3. There are matrices whose left-inverse and right-inverse are not equal to each other, i.e.,  
 ∃A, B, C such that BA = I and AC = I.  
 $\quad$ False  
  
4. A matrix has full-rank if and only if it is invertible.  
$\quad$ Not sure but the inverse is true though, a matrix is invertible if and only if it has a fill rank.  
  
5. All symmetric matrices are invertible.  
$\quad$ Only symmetric matrices with full rank are invertible.  
  
6. A matrix is invertible if all eigenvalues are distinct.  
$\quad$Ans:If algebraic multiplicty is >1 for a given $\lambda$ then $\lambda$s are not distinct.  
<div style="border:solid">Not sure of invertibility in relation to multiplicity of an eigen value.</div>  
But A matrix is invertible if and only if it has all non-zero eigen values. But a given eigen value is said to be repeated if it's geometric multiplicity is >1.  
So the statement could be False.  
The statement should be "A matrix is invertible if all eigenvalues are non-zero real values." This would imply that A is Hermitian matrix and thus is invertible.
  
7. A matrix is diagonalizable if and only if it is invertible.  
$\quad$Ans:Invertibility has nothing to do with diagonalizability as $A=UDU^-1$ for symmetric matrices via EVD and $A=U\sum V^T$ for non symmetric matrices via  SVD

###### Problem A-2  
1. Find an orthonormal basis of the subspace of $R^5$ spanned by $v_1$, $v_2$, and
$v_3$, where $v_1$ = (1, 0, 1, 0, 1), $v_2$ = (1, 1, 1, 0, 0), and $v_3$ = (0, 0, 1, 1, 1), using Gram-Schmidt
process.
2. Complete the basis found in (a), into an orthonormal basis of R5.  
3. Find the matrix U which transforms the basis found in (b) into the standard basis of R5.  

In [33]:
import numpy as np

A=np.column_stack(([1,0,1,0,1],[1,1,1,0,0],[0,0,1,1,1]))
print(A)
V1=np.transpose([1,0,1,0,1])
V2=np.transpose([1,1,1,0,0])
V3=np.transpose([0,0,1,1,1])

U1=V1
U2=V2-(np.matmul(np.transpose(U1),V2)/np.matmul(np.transpose(U1),U1))*U1
U3=V3-(np.matmul(np.transpose(U1),V3)/np.matmul(np.transpose(U1),U1))*U1 - (np.matmul(np.transpose(U2),V3)/np.matmul(np.transpose(U2),U2))*U2

print(U1)
print(U2)
print(U3)
print("Test Orthonormality")
print(np.matmul(np.transpose(U1),U2))
print(np.matmul(np.transpose(U1),U3))
print(np.matmul(np.transpose(U2),U3))
print("All vectors are perpendicular to each other as the dot products are very close to zero.")

E1=U1/np.matmul(np.transpose(U1),U1)**0.5
E2=U2/np.matmul(np.transpose(U2),U2)**0.5
E3=U3/np.matmul(np.transpose(U3),U3)**0.5

U=np.column_stack((E1,E2,E3))
print("U=" + str(U))
#Tranpose(U).U=I as U is an orthonormal basis.
print("Test=" + str(np.matmul(np.transpose(U),U)))


[[1 1 0]
 [0 1 0]
 [1 1 1]
 [0 0 1]
 [1 0 1]]
[1 0 1 0 1]
[ 0.33333333  1.          0.33333333  0.         -0.66666667]
[-0.6  0.2  0.4  1.   0.2]
Test Orthonormality
1.1102230246251565e-16
1.1102230246251565e-16
-5.551115123125783e-17
All vectors are perpendicular to each other as the dot products are very close to zero.
U=[[ 0.57735027  0.25819889 -0.47434165]
 [ 0.          0.77459667  0.15811388]
 [ 0.57735027  0.25819889  0.31622777]
 [ 0.          0.          0.79056942]
 [ 0.57735027 -0.51639778  0.15811388]]
Test=[[ 1.00000000e+00  5.55111512e-17  5.55111512e-17]
 [ 5.55111512e-17  1.00000000e+00 -5.55111512e-17]
 [ 5.55111512e-17 -5.55111512e-17  1.00000000e+00]]


###### Problem B-1. 
Decide whether the following statements about a singular value decomposition $A = UΣV^T$ are true or false. EXPLAIN the reason.  
1.  The number of non-zero diagonal entries of Σ is equal to the rank of A.  
$\quad$True.  
  
2. Σ is uniquely determined up to permuting the rows and columns.  
$\quad$  Don't understand the question  
  
3. If A is a n × n matrix, then U and V can be chosen so that U = V .
$\quad$ False.  
$\quad$In $n × n$ case it wouldn't be $A=UDV^T$ but it would be $A=UDV^{-1}$.  
$\quad$Both would be the same only when $V^T=V^{-1}$. This would be the case when A is Hermititan(or real symmetric matrix).

4. If A is a symmetric n × n matrix, then U and V can be chosen so that U = V  
$\quad$Not is A is a symmetric n × n matrix, with complex numbers on non-diagonal. In which case it needs to be a Hermitian for this to be True. That is $A=A^*$, that is $A=\bar{A}^{T}$. This is not the case when A is symmetric as below:-
$\quad$$A=\left[{\begin{array}{cc} 1&i\\i&1 \end{array}}\right]$  


###### Problem B-2. 
Prove that the matrices $AA^T$ and $A^TA$ have the same set of non-zero eigenvalues.
(Hint: consider the singular value decomposition of A)

$A=U\sum V^T$  
$\quad\implies A^T=V(U\sum )^T$  
$\quad\implies A^T=V\sum^TU^T$  
$A^TA=V\sum^2V^T$  
$AA^T=U\sum V^TV\sum^TU^T$ Since $V$ is an othogonal matrix as $AA^T$ is real symmetric, for orthogonal matrices $VV^T=V^TV=I$ and $V^T=V^{-1}$  
$\quad\implies AA^T=U\sum \sum^TU^T$  
$\quad\implies AA^T=U\sum^2U^T$ 

In [63]:
import numpy as np
#A is a Shear Transformation matrix
A=[[1,4],[0,1]]
B=[[1],[1]]

BT=np.matmul(A,B)
print(str(np.array(A)) + "\t\n Transforms \n" + str(np.array(B)) + "\t\n to \n" + str(BT))

l,v=np.linalg.eig(A)
print("Lambdas=" + str(l))
print("Vectors=\n" + str(v))

v1=np.array([[v[0,0]],[v[1,0]]])
print(v1)

#U=Av/sigma
u1=np.matmul(A,v1)
U=np.column_stack((u1,u1))
V=np.column_stack((v1,v1))
D=np.array([[l[0],0],[0,l[1]]])
print("U")
print(U)
print("D")
print(D)
print("V")
print(V)

#A=UZV(T)
print(np.matmul(U,D))
print(np.matmul(np.matmul(U,D),np.transpose(V)))

#Here 

[[1 4]
 [0 1]]	
 Transforms 
[[1]
 [1]]	
 to 
[[5]
 [1]]
Lambdas=[1. 1.]
Vectors=
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  5.55111512e-17]]
[[1.]
 [0.]]
U
[[1. 1.]
 [0. 0.]]
D
[[1. 0.]
 [0. 1.]]
V
[[1. 1.]
 [0. 0.]]
[[1. 1.]
 [0. 0.]]
[[2. 0.]
 [0. 0.]]
