$e^x=1+x+\frac{x^2}{2!}+\frac{x^3}{3!}+.....$
--
$\qquad\qquad$Remember that $n!$ has a lower bound of $a^n$. $n!$ increases faster than $a^n$ for any real $a$ thus the above series is converging.

$1+x \leq e^x \leq 1+ x + x^2$
--
$\qquad\qquad$for $|x| \leq 1$
--

Thus 

$e^x\rightarrow 1+x$ as $x\rightarrow 0$
--



$\operatorname{Lt}_{n\rightarrow\infty}\left(1+\frac{x}{n}\right)^n=e^x$
--

$\operatorname{Lt}_{n\rightarrow\infty}\left(\frac{n^b}{a^n}\right)=0$
--
$\qquad\qquad$ for all $a>1$  
--


$\operatorname{Lt}_{n\rightarrow\infty}\left(\frac{\operatorname{lg}^bn}{(2^a)^{\operatorname{lg}n}}\right)=0$  
$\operatorname{Lt}_{n\rightarrow\infty}\left(\frac{\operatorname{lg}^bn}{2^{a{\operatorname{lg}n}}}\right)=0$  
$\operatorname{Lt}_{n\rightarrow\infty}\left(\frac{\operatorname{lg}^bn}{2^{{\operatorname{lg}n^a}}}\right)=0$  
$\operatorname{Lt}_{n\rightarrow\infty}\left(\frac{\operatorname{lg}^bn}{{{n^a}}}\right)=0$  
--

$\qquad\qquad$ for all $2^a>1 \Rightarrow a>0$  
--

Thus $\operatorname{lg}^b n = o(n^a)$  for any constant $a>0$


Proof:-
--
$\operatorname{Lt_{n\rightarrow\infty}}(1+\frac{x}{n})^n=e^x$
--

$(1+x)^1=1+x$  
$(1+x)^2=1+2x+x^2$  
$(1+x)^3=1+3x+3x^2+x^3$  
$(1+x)^4=(1+2x)^2+2x^2+4x^3+x^4$  
$\qquad=1+4x+4x^2+2x^2+4x^3+x^4$  
$\qquad=1+4x+6x^2+4x^3+x^4$  
$(1+x)^5=1+5x+\frac{5!}{2!3!}x^2+\frac{5!}{2!3!}x^3+5x^4+x^5$  
.  
.  
.  
as $n\rightarrow\infty$  
$(1+\frac{x}{n})^n=1+n\frac{x}{n}+\frac{(n-1)n}{2!}\left(\frac{x}{n}\right)^2+\frac{(n-3)(n-1)n}{3!}\left(\frac{x}{n}\right)^3.....$  
$\qquad\qquad=1+x+\frac{x^2}{2!}+\frac{x^3}{3!}.....$  



### Recursion formula for sum of series
We need to derive formula for $\operatorname{S}(n,i)=\sum_{k=1}^n k^i$  
$(k+1)^{i+1}=\sum_{j=0}^{i+1} \operatorname {^{(i+1)}C_j}k^j$  
$(k+1)^{i+1}= k^{i+1} + \sum_{j=0}^i \operatorname {^{(i+1)}C_j}k^j$  
$(k+1)^{i+1} - k^{i+1} = \sum_{j=0}^i \operatorname {^{(i+1)}C_j}k^j$  
$(n+1)^{i+1} - 1 = \sum_{k=1}^n \sum_{j=0}^i \operatorname {^{(i+1)}C_j}k^j$  
$(n+1)^{i+1} - 1 =   \sum_{j=0}^i \operatorname {^{(i+1)}C_j} \sum_{k=1}^n k^j$  
$(n+1)^{i+1} - 1 =  (i+1)\sum_{k=1}^n k^i +\sum_{j=0}^{i-1} \operatorname {^{(i+1)}C_j} \sum_{k=1}^n k^j$  
$(n+1)^{i+1} - 1 =  (i+1)\operatorname{S}(n,i) +\sum_{j=0}^{i-1} \operatorname {^{(i+1)}C_j} \operatorname{S}(n,j)$  
### $\operatorname{S}(n,i)=\frac{1}{i+1}\left( (n+1)^{i+1} - 1 - \sum_{j=0}^{i-1} \operatorname {^{(i+1)}C_j} \operatorname{S}(n,j) \right)$  


### Linear Recurion Series

$\sum_{i=0}^k a_ix_{n+i}=0$ is linear recursive function of the order of k. Any $x_n$ can be defined by using previous $k$, $x_{n-i}$,$i=1:k$ in the series.  

Three Step Process.

1. Find the recursion dependence without any "n" in the definition of $x_n$. Gives the order $k$. That is $x_{n+k+1}=\sum_{j=0}^ka_jx_{n+j}$
2. Find the co-efficients of the characteristic polynomial or the order of k. And find it's k roots $\lambda_i$
3. Find the values for first $k$ in the series
4. Solve the linear system of equations to get the $C_j$ using AC=x.

What we have is that  
$\sum_{j=1}^k C_j\lambda_j^n=x_n$ Thus the solution for the system of $C_j\lambda_j^n$ would hold for $x_n$.  

 * Now $C\lambda_j^n$ is a linear recursive series, as  
$\sum_{i=0}^k a_iC\lambda_j^{n+i}=C\lambda_j^n\sum_{i=0}^k a_i\lambda_j^i=C\lambda_j^n\operatorname P(\lambda_j)=0$  
Where $\operatorname P(z)$ is a characteristic polynomial for the original linear recursive series and $\lambda_j$ is the $j^{th}$ root of the polynomial.  
 * Now the sum of $k^{th}$ order linear recursive series is also a linear recursive series thus $\sum_{i=1}^k C_i\lambda_i^n$ is a linear recursive series.  

If we have repeated roots then multiplicity of $\lambda_j$ as $m_j>1$  in which case  
$\sum_{j=1}^p \left(\sum_{i=0}^{m_j} C_{i,j}n^i\right)\lambda_j^n=x_n$

##### Example work out.

$x_{n+1}=x_n+(n+1)^2\qquad\qquad$      (1)  $\qquad\rightarrow$ we have an n term still  
$\qquad x_1=0+(0+1)^2=1$  
$x_{n+2}=x_{n+1}+(n+2)^2\qquad\qquad$    (2)  
$x_{n+2}=2x_{n+1}-x_n+(2n+3)\qquad$    (2)-(1)=(3)  $\qquad\rightarrow$ we have an n term still  
$\qquad x_2=2*1-0+(2*0+3)=5$  
$x_{n+3}=2x_{n+2}-x_{n+1}+(2(n+1)+3)\qquad$    (4)  
$x_{n+3}=3x_{n+2}-3x_{n+1}+x_n+2\qquad$    (4)-(3)=(5)    $\qquad\rightarrow$ we have a constant term yet  
$\qquad x_3=3*5-3*1+0+2=14$  
$x_{n+4}=3x_{n+3}-3x_{n+2}+x_{n+1}+2\qquad$    (6)  
$x_{n+4}=4x_{n+3}-6x_{n+2}+4x_{n+1}-x_n\qquad$    (6)-(5)=(7)     $\qquad\rightarrow \sum_{i=0}^ka_ix_{n+i}=0$  
$\qquad x_4=4*14-6*5+4*1-0=30$  
Now the characteristic polynomial of the this linear recursive series is  
$P(z)=z^4-4z^3+6z^2-4z-1=0$  
$\rightarrow(z-1)^4=0$  

As $\lambda=1$ and it's multiplicity is 4, we have  
$x_n=C_0n^0\lambda^n + C_1n^1\lambda^n + C_2n^2\lambda^n + C_3n^3\lambda^n$  
$x_n=C_0 + C_1n + C_2n^2 + C_3n^3$  


In [7]:
import numpy as np
A=[[1,1,1,1],[1,2,4,8],[1,3,9,27],[1,4,16,64]]
print(A)
C=[1,5,14,30]
#print(np.linalg.inv(A))
print(np.matmul(np.linalg.inv(A),C))

[[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]]
[0.         0.16666667 0.5        0.33333333]


We have
$C_0=0$  
$C_1=1/6$  
$C_2=1/2$  
$C_3=1/3$  

We have  
$x_n=0+n/6+n^2/2+n^3/3$  
$x_n=\frac{n+3n^2+2n^3}{6}$    
$x_n=\frac{n(1+3n+2n^2)}{6}$  
$x_n=\frac{n(n+1)(2n+1}{6}$  


##### Example 2

Find the general form of the sequence $(x_n)_{n\geq 0}$ satisfying the linear re- cursion  
    $\qquad x_{n+3} = 2x_{n+l} + x_n$  
with $x_0=1$, $x_1=-1$ and $x_2=1$.  

$P(z)=z^3-2z-1=0$  
$z(z^2-1)-(z+1)=0$  
$(z+1)(z^2-z-1)=0$  
$z=-1$ or
$z=\frac{1\pm\sqrt{1^2-4*1*-1}}{2*1}$  
$z=\frac{1\pm\sqrt{5}}{2}$  
$x_n=\sum_{j=1}^k C_j\lambda_j^n$  
$AC=x$  
$A=\left[\begin{array}{ccc} -1^0& \left(\frac{1+\sqrt{5}}{2}\right)^0& \left(\frac{1-\sqrt{5}}{2}\right)^0\\
-1& \left(\frac{1+\sqrt{5}}{2}\right)^1 &\left(\frac{1-\sqrt{5}}{2}\right)^1\\
-1^2& \left(\frac{1+\sqrt{5}}{2}\right)^2 &\left(\frac{1-\sqrt{5}}{2}\right)^2\end{array}\right]$  
$x=\left[\begin{array}{c}1\\-1\\1\end{array}\right]$

In [29]:
import numpy as np
from math import sqrt
root_p=(1+5**0.5)/2.
root_n=(1-5**0.5)/2.
r=np.array([-1,root_p,root_n])
A=np.vstack((r**0,r,r**2))
print(A)
x=np.transpose(np.array([1,-1,1]))
print(x)
print(np.matmul(np.linalg.inv(A),x))


[[ 1.          1.          1.        ]
 [-1.          1.61803399 -0.61803399]
 [ 1.          2.61803399  0.38196601]]
[ 1 -1  1]
[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
1.4142135623730951


Thus $C_1=1$ and $C_2=C_3=0$ showing that...

$x_n= C_1\lambda_1^n$  
$x_n= 1*-1^n$  
$x_n=-1^n \quad\forall\quad n\geq0$




##### Example 3
The sequence $(x_n)_{n\geq 0}$ satisfies the recursion  
$x_{n+l} = 3x_n+2\quad\forall\quad n\geq0$  
with $x_0=1$.  
(i) Show that the sequence $(x_n)_{n\geq0}$ satisfies the linear recursion  
$x_{n+2} = 4x_{n+l} - 3x_n \quad\forall\quad n\geq0$  
with $x_0=1$ and $x_1=5$.  
(ii) Find the general formula for $x_n\quad\forall\quad n\geq0$

---
$x_{n+1}=3x_n+2\qquad$(1)  
$x_{n+2}=3x_{n+1}+2\qquad$ by n=n+1 in(1)$\qquad$ (2)  
$x_{n+2}=4x_{n+1}-3x_n\qquad$(2)-(1)$\qquad$(3) 

Characteristic polynomial  
$P(z)=z^2-4z+3=0$  
$P(z)=(z-3)(z-1)=0$  
$\lambda_1=3$ and $\lambda_2=1$  
$AC=x$  
$C=\left[\begin{array}{c} C_1\\C_2\end{array}\right]$  
$A=\left[\begin{array}{cc} 3^0&1^0\\3^1&1^1\end{array}\right]$  
$x=\left[\begin{array}{c} 1\\5\end{array}\right]$  

$C_1=2$ and $C_2=-1$  

Thus 
$x_n=\sum_{j=1}^2 C_j\lambda_j^n$  
$x_n=2*3^n -1*1^n$  
$x_n=2*3^n-1$  


##### Example 3

With multiplicity of a root being=2.

Characterristic equation is  
$P(z)=z^3-5z^2+7z-3=0$  
$\implies (z-3)(z-1)^2=0$  
$\lambda_1=3$ and $\lambda_2=1$ with multiplicity of 2.

Now given $x_0=1,x_1=5,x_2=18$  
$A=\left[\begin{array}{ccc} \lambda_1^0&\lambda_2^0&0*\lambda_2^0\\
                            \lambda_1^1&\lambda_2^1&1*\lambda_2^1\\
                            \lambda_1^2&\lambda_2^2&2*\lambda_2^2\\\end{array}\right]$  
$A=\left[\begin{array}{ccc} 3^0&1^0&0*1^0\\
                            3^1&1^1&1*1^1\\
                            3^2&1^2&2*1^2\\\end{array}\right]$  
$A=\left[\begin{array}{ccc} 1&1&0\\
                            3&1&1\\
                            9&1&2\\\end{array}\right]$  
$x=\left[\begin{array}{c} 1\\
                          5\\
                          18\\\end{array}\right]$  

                            

In [30]:
A=np.array([[1,1,0],
            [3,1,1],
            [9,1,2]])
x=[1,5,18]
print(np.matmul(np.linalg.inv(A),x))
        

[ 2.25 -1.25 -0.5 ]


$C_1=9/4,C_2=-5/4,C_3=-1/2$  
$x_n=\frac{9}{4}3^n-\frac{5}{4}-\frac{n}{2}$  
$x_n=\frac{3^{n+2} -2n-5}{4}$    