#### TODO 

1. Verify the formulae below once.
2. Prove that it is not worth exercising an American Call Option.
3. Derive Formula for Barrier Options
4. Relationship between Heat Equation and Black Scholes.



Deep in the money put options are worth less than K-S.
Also Deep in the money put option of shorter maturity is worth more than longer maturity put option.
Buy longer dated put option and sell shorter dated deep in the money put option. Once the shorter dated maturity put option expires you get the put option for the remaining time for free.

## Black Scholes



* Put Call Parity  
$P+Se^{-q(T-t)}-C=Ke^{-r(T-t)}$  
* Call Option Price(at time $t$ with expiry=$T$  
$C=Se^{-q(T-t)}N(d1)-Ke^{-r(T-t)}N(d2)$  
$d1=\frac{ln(\frac{S}{K})+(r-q+\frac{\sigma^2}{2})(T-t)}{\sigma\sqrt{T-t}}$  
$d2=d1-\sigma\sqrt {T-t}$  
$\quad=\frac{ln(\frac{S}{K})+(r-q-\frac{\sigma^2}{2})(T-t)}{\sigma\sqrt{T-t}}$  
* Put Option Price(at current time 0 and expiry=$t$)  
$P=Ke^{-rt}-Se^{-qt}+C$  
$\quad=Ke^{-rt}-Se^{-qt}+Se^{-qt}N(d1)-Ke^{-rt}N(d2)$  
$\quad=Ke^{-rt}(1-N(d2))-Se^{-qt}(1-N(d1))$  
$\quad=Ke^{-rt}N(-d2)-Se^{-qt}N(-d1)$  
* Down and out Call Option Price with B<K is  

<div style="border:dashed;text-align:center">$V(S,K,T)=C(S,K,T) - \left(\frac{B}{S}\right)^{2a}\, C(\frac{B^2}{S},K,T)\,\,\,Where\,\,a=\frac{r-q}{\sigma^2}-\frac{1}{2}$</div>   

* Option Delta  
$\Delta_C=e^{-q(T-t)}N(d_1)$  
$\Delta_P=-e^{-q(T-t)}N(-d_1)$  
* Option Gamma  
$\Gamma_C=\Gamma_P=\frac{e^{-q(T-t)}}{S\sigma\sqrt{T-t}}e^{-\frac{d_1^2}{2}}$  
* Option Vega  
$\kappa_C=\kappa_P=\frac{Se^{-qt}\sqrt t}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}$   
* Option Rho  
$\rho_C=(T-t)Ke^{-r(T-t)}N(d_2)$  
$\rho_P=-(T-t)Ke^{-r(T-t)}N(-d_2)$  
* Option Theta  
$\Theta_C=qSe^{-q(T-t)}N(d_1)-rKe^{-r(T-t)}N(d_2)-\frac{S\sigma e^{-q(T-t)} }{2\sqrt{2\pi(T-t)}}e^{-\frac{d_1^2}{2}}$  
$\Theta_P=-qSe^{-q(T-t)}N(-d_1)+rKe^{-r(T-t)}N(-d_2)-\frac{S\sigma e^{-q(T-t)} }{2\sqrt{2\pi(T-t)}}e^{-\frac{d_1^2}{2}}$  
* Option Volga  
$\frac{d\kappa_C}{d\sigma}=\frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}\frac{d_1d_2}{\sigma}$  
* Option Vanna  
$\frac{d\kappa_C}{dS}=\frac{d\Delta_C}{d\sigma}=-\frac{e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}\frac{d_2}{\sigma}$  
**Significance of d_1 and d_2**  
$N(d_2)$ is the probability of $S_T\geq K$  
$N(-d_2)$ is the probability of $S_T\leq K$  
$N(d1)$ is the Call option delta when there is no dividend  
$-N(-d1)$ is the Put option delta  when there is no dividend  
Thus P-C is a perfect momentary hedge for a portfolio with one Stock as the sum of deltas is one. Which is also the case in a put call parity.


### Deriving Option Greeks
**Note for future derivations**  
$Se^{-q(T-t)}=Ke^{-r(T-t)}\frac{S}{K}e^{(r-q)(T-t)}$  
$\quad=Ke^{-r(T-t)}\operatorname{exp}( log(\frac{S}{K}) +(r-q)(T-t))$  
$\qquad\qquad log(\frac{S}{K}) +(r-q)(T-t)=log(\frac{S}{K}) +(r-q+\frac{\sigma^2}{2})(T-t) -\frac{\sigma^2}{2}(T-t)$  
$\qquad\qquad log(\frac{S}{K}) +(r-q)(T-t)=d_1\sigma\sqrt{T-t} -\frac{\sigma^2}{2}(T-t)$  
$Se^{-q(T-t)}=Ke^{-r(T-t)}\operatorname{exp}(d_1\sigma\sqrt{T-t} -\frac{\sigma^2}{2}(T-t))$  
Multiply both sides by $e^{-\frac{d_1^2}{2}}$  
$Se^{-q(T-t)}e^{-\frac{d_1^2}{2}}=Ke^{-r(T-t)}\operatorname{exp}(d_1\sigma\sqrt{T-t} -\frac{\sigma^2}{2}(T-t)-\frac{d_1^2}{2})$  
$\quad=Ke^{-r(T-t)}\operatorname{exp}(-\frac{(d_1-\sigma\sqrt{T-t})^2}{2})$  
$\quad=Ke^{-r(T-t)}\operatorname{exp}(-\frac{d_2^2}{2})$  
$Se^{-q(T-t)}e^{-\frac{d_1^2}{2}}=Ke^{-r(T-t)}e^{-\frac{d_2^2}{2}}$   
<div style="border:dashed;text-align:center">
$Se^{-q(T-t)}N'(d_1)=Ke^{-r(T-t)}N'(d_2)$</div>  





#### Option Delta Derivation
$C=Se^{-qt}N(d_1)-Ke^{-rt}N(d_2)$  
$\frac{dC}{dS}=e^{-qt}N(d1) + Se^{-qt}N'(d_1)\left(\frac{dd_1}{dS}-\frac{dd_2}{dS}\right)$  
$\qquad\qquad$ From earlier $Se^{-qt}N'(d_1)=Ke^{-rt}N'(d_2)$   
$\frac{dd_1}{dS}=\frac{1}{\sigma\sqrt{T-t}}\frac{K}{S}\frac{1}{K}=\frac{1}{S\sigma\sqrt{T-t}}=\frac{dd_2}{dS}$  
Thus  
$\Delta_C=e^{-q(T-t)}N(d_1)$  
$\Delta_P=-e^{-q(T-t)}N(-d_1)\qquad$Could be derived from put call parity equation  


#### Option Gamma Derivation  
$\frac{d\Delta_C}{dS}=e^{-q(T-t)}N'(d_1)\frac{1}{S\sigma\sqrt{T-t}}$  
$\frac{d\Delta_C}{dS}=\frac{e^{-q(T-t)}e^{-\frac{d_1^2}{2}}}{S\sigma\sqrt{2\pi(T-t)}}$  
$\Gamma_C=\Gamma_P=\frac{e^{-q(T-t)}e^{-\frac{d_1^2}{2}}}{S\sigma\sqrt{2\pi(T-t)}}$  


#### Option Vega Derivation  
$\frac{dC}{d\sigma}=Se^{-qt}N'(d_1)\left(\frac{dd_1}{d\sigma}-\frac{dd_2}{d\sigma}\right)$  
$\frac{dd_1}{d\sigma}=-\frac{log\frac{S}{K}+(r-q+\sigma^2/2)t}{\sigma^2\sqrt{t}} +\frac{\sigma t}{\sigma\sqrt t}$
$\qquad=\frac{A}{\sigma^2\sqrt t} - \frac{t\sigma^2/2}{\sigma^2\sqrt{t}}+\frac{\sigma t}{\sigma\sqrt t}$  
$\qquad=\frac{A}{\sigma^2\sqrt t} +\frac{\sqrt t}{2}$  
$\frac{dd_1}{d\sigma}-\frac{dd_2}{d\sigma}=\frac{A}{\sigma^2\sqrt t} +\frac{\sqrt t}{2} -(\frac{A}{\sigma^2\sqrt t} -\frac{\sqrt t}{2})$  
$\frac{dd_1}{d\sigma}-\frac{dd_2}{d\sigma}=\sqrt t$  
$\frac{dC}{d\sigma}=Se^{-qt}N'(d_1)\sqrt t$  
$\frac{dC}{d\sigma}=\frac{Se^{-qt}e^{-\frac{d_1^2}{2}}\sqrt t}{\sqrt{2\pi}}$   
$\kappa_C=\frac{Se^{-qt}e^{-\frac{d_1^2}{2}}\sqrt t}{\sqrt{2\pi}}$   


#### Option Rho Derivation  
$\frac{dC}{dr}=(T-t)Ke^{-r(T-t)}N(d_2) +Se^{-q(T-t)}N'(d_1)\left(\frac{dd_1}{dr}-\frac{dd_2}{dr}\right)$  
$\frac{dd_1}{dr}=\frac{T-t}{\sigma\sqrt{T-t}}$  
$\frac{dd_1}{dr}-\frac{dd_2}{dr}=0$  
$\frac{dC}{dr}=-(T-t)Ke^{-r(T-t)}N(d_2)$  
$\rho_C=-(T-t)Ke^{-r(T-t)}N(d_2)$  


#### Option Theta Derivation  
$\frac{dC}{dt}=qSe^{-q(T-t)}N(d_1)-rKe^{-r(T-t)}N(d_2)+Se^{-q(T-t)}N'(d_1)\left(\frac{dd_1}{dt}-\frac{dd_2}{dt}\right)$  
$\frac{dd_1}{dt}=\frac{1}{2}\frac{log\frac{S}{K}+(r-q+\sigma^2/2)(T-t)}{\sigma(T-t)\sqrt{T-t}}-\frac{r-q+\sigma^2/2}{\sigma\sqrt{T-t}}$  
$\qquad=A+\frac{1}{2}\frac{\sigma^2/2}{\sigma\sqrt{T-t}}-\frac{\sigma^2/2}{\sigma\sqrt{T-t}}$  
$\qquad=A-\frac{\sigma}{4\sqrt{T-t}}$  
$\frac{dd_1}{dt}-\frac{dd_2}{dt}=A-\frac{\sigma}{4\sqrt{T-t}}-(A+\frac{\sigma}{4\sqrt{T-t}})$  
$\frac{dd_1}{dt}-\frac{dd_2}{dt}=-\frac{\sigma}{2\sqrt{T-t}}$  
$\frac{dC}{dt}=qSe^{-q(T-t)}N(d_1)-rKe^{-r(T-t)}N(d_2)-Se^{-q(T-t)}N'(d_1)\frac{\sigma}{2\sqrt{T-t}}$  
$\frac{dC}{dt}=qSe^{-q(T-t)}N(d_1)-rKe^{-r(T-t)}N(d_2)-\frac{S\sigma e^{-q(T-t)} e^{-\frac{d_1^2}{2}}}{2\sqrt{2\pi(T-t)}}$  
$\Theta_C=qSe^{-q(T-t)}N(d_1)-rKe^{-r(T-t)}N(d_2)-\frac{S\sigma e^{-q(T-t)} e^{-\frac{d_1^2}{2}}}{2\sqrt{2\pi(T-t)}}$  


#### Derive Volga and Vanna  
$\frac{dC}{d\sigma}=Se^{-q(T-t)}N'(d_1)\left(\frac{dd_1}{d\sigma}-\frac{dd_2}{d\sigma}\right)$  
$\frac{dC}{d\sigma}=S\sqrt{T-t}e^{-q(T-t)}N'(d_1)$  
$\frac{dC}{d\sigma}=S\sqrt{T-t}e^{-q(T-t)}N'(d_1)$  


#### Derive Volga  
$\frac{d^2C}{d\sigma^2}=\frac{d}{d\sigma}(\frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}})$  
$\qquad=\frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}(-d_1)\frac{dd_1}{d\sigma}$  
$\frac{dd_1}{d\sigma}=-\frac{log\frac{S}{K} + (r-q+\sigma^2/2)(T-t)}{\sigma^2\sqrt{T-t}} +\frac{\sigma(T-t)}{\sigma\sqrt{T-t}}$  
$\qquad=-\frac{d_1}{\sigma} +\sqrt{T-t}$  
$d_1\frac{dd_1}{d\sigma}=-\frac{d_1^2}{\sigma} +d_1\sqrt{T-t}$  
$\frac{d^2C}{d\sigma^2}=\frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}d_1(\frac{d_1}{\sigma}-\sqrt{T-t})$  
$\frac{d^2C}{d\sigma^2}=\frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}d_1(\frac{d_2}{\sigma})$  
$\frac{d^2C}{d\sigma^2}=\frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}\frac{d_1d_2}{\sigma}$  

$P=Ke^{-r(T-t)}-Se^{-q(T-t)}+C$  
Volga of both put and call options are the same.  
Vanna should also be equal as Vega is same the derivative of Vega should also be the same.  


#### Derive Vanna  
$\frac{d^2C}{dSd\sigma}=\frac{d}{dS}(\frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}})$  
$\qquad=\frac{\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}} + \frac{S\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}(-d_1)\frac{dd_1}{dS}$  
$\frac{dd_1}{dS}=\frac{1}{S\sigma\sqrt{T-t}}$  
$\frac{d^2C}{dSd\sigma}=\frac{\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}} - \frac{S\sqrt{T-t}e^{-q(T-t)}}{S\sigma\sqrt{2\pi(T-t)}}e^{-\frac{d_1^2}{2}}d_1$  
$\frac{d^2C}{dSd\sigma}=\frac{\sqrt{T-t}e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}} - \frac{e^{-q(T-t)}}{\sigma\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}d_1$  
$\frac{d^2C}{dSd\sigma}=\frac{e^{-q(T-t)}e^{-\frac{d_1^2}{2}}}{\sqrt{2\pi}}(\sqrt{T-t} - \frac{d_1}{\sigma})$  
$\frac{d^2C}{dSd\sigma}=-\frac{e^{-q(T-t)}}{\sqrt{2\pi}}e^{-\frac{d_1^2}{2}}\frac{d_2}{\sigma}$  

## Deriving Black Scholes Formula

$\frac{S(t+\delta t)-S(t)}{S(t)\delta t}=r+\frac{\sigma}{\sqrt{\delta t}}Z$  
$dS= rSdt+\sigma SdW$  
$\qquad\qquad$Where $dW=\sqrt t Z dt$ is a Weiner process.  
The solution for this SDE is  

<div style="border:dotted;text-align:center;word-wrap:break-word">$log(\frac{S_T}{S_0})=(r-q-\frac{\sigma^2}{2})T+\sigma\sqrt T Z$  
$S_T=S_0e^{(r-q-\frac{\sigma^2}{2})T+\sigma\sqrt T Z}$  
</div>
Now for Call Option Value $C_T$ at Maturity $T$ is defined as: 

$C_T=$  
$\qquad\qquad=S_T-K$  if $S_T\geq K$  
$\qquad\qquad=0$  otherwise  

**For $S_T\geq K$**  
$S_T \geq K \implies S_0e^{(r-q-\frac{\sigma^2}{2})T+\sigma\sqrt TZ} \geq K$  
$\quad\implies(r-q-\frac{\sigma^2}{2})T+\sigma\sqrt TZ \geq log(\frac{K}{S_0})$  
$\quad\implies\sigma\sqrt TZ \geq log(\frac{K}{S_0})-(r-q-\frac{\sigma^2}{2})T$  
$\quad\implies Z \geq\frac{log(\frac{K}{S_0})-(r-q-\frac{\sigma^2}{2})T}{\sigma\sqrt T}$  
$\quad\implies Z \geq-\frac{log(\frac{S_0}{K})+(r-q-\frac{\sigma^2}{2})T}{\sigma\sqrt T}$  
$\quad\implies Z \geq-d_2$  

Now Rewriting Call Option Value  
$C_T=$  
$\qquad\qquad=S_T-K$  if $Z\geq -d_2$  
$\qquad\qquad=0$  otherwise  

Discount for Call Option price at t=0  
$C_0=$  
$\qquad\qquad=e^{-rT}(S_T-K)$  if $Z\geq -d_2$  
$\qquad\qquad=0$  otherwise  

$C_0=$  
$\qquad\qquad=e^{-rT}(S_0e^{(r-q-\frac{\sigma^2}{2})T+\sigma\sqrt T Z}-K)$  if $Z\geq -d_2$  
$\qquad\qquad=0$  otherwise  

Now evaluating only the non-zero part of price of Call Option  
$C_0=\frac{e^{-rT}}{\sqrt{2\pi}}\int_{-d_2}^{\infty}{(S_0e^{(r-q-\frac{\sigma^2}{2})T+\sigma\sqrt T x}-K) e^{-\frac{x^2}{2}}\,dx}$  
$\qquad=\frac{S_0e^{-qT}}{\sqrt{2\pi}}\int_{-d_2}^{\infty}e^{-\frac{\sigma^2}{2}T+\sigma\sqrt Tx-\frac{x^2}{2}}dx-\frac{Ke^{-rT}}{\sqrt{2\pi}}\int_{-d_2}^{\infty}e^{-\frac{x^2}{2}}dx$  
$\qquad=\frac{S_0e^{-qT}}{\sqrt{2\pi}}\int_{-d_2}^{\infty}e^{-\frac{(x-\sigma\sqrt T)^2}{2}}dx-Ke^{-rT}N(d_2)\qquad$Now substitute $t=x-\sigma\sqrt T$    
$\qquad=\frac{S_0e^{-qT}}{\sqrt{2\pi}}\int_{-d_2-\sigma\sqrt T}^{\infty}{e^{-\frac{t^2}{2}}\,dt}-Ke^{-rT}N(d_2)\qquad$ As $d_1=d_2+\sigma\sqrt T$    
$\qquad=\frac{S_0e^{-qT}}{\sqrt{2\pi}}\int_{-d_1}^{\infty}e^{-\frac{t^2}{2}}dt-Ke^{-rT}N(d_2)\qquad$  
$\qquad=S_0e^{-qT}N(d_1)-Ke^{-rT}N(d_2)\qquad$  



### Relationship of a delta neutral portfolio to $\Theta$, $\Gamma$ and $\sigma$  

Taylor Expansion of Option Value V(S,T)  

$V(S+dS,T+dt) = V(S,T) +dS\frac{\delta V(S,T)}{\delta S} + dt\frac{\delta V(S,T)}{\delta t} + \frac{(dS)^2}{2}\frac{\delta^2 V(S,T)}{\delta S^2} + \frac{(dt)^2}{2}\frac{\delta^2 V(S,T)}{\delta t^2} +dS\,dt\frac{\delta^2V(S,T)}{\delta S\delta t} + O((dS)^3) + O((dt)^3)$  
$V(S+dS,T+dt) \approx V(S,T) +dS\frac{\delta V(S,T)}{\delta S} + dt\frac{\delta V(S,T)}{\delta t} + \frac{(dS)^2}{2}\frac{\delta^2 V(S,T)}{\delta S^2} $Ignoring the higher order dt  
$V(S+dS,T+dt) \approx V(S,T) +dS\Delta + \Theta dt + \frac{(dS)^2}{2}\Gamma $  
$dV-\Delta dS\approx \Theta dt + \frac{(dS)^2}{2}\Gamma $  

Remember the Log Normality assumption for Stock Price  
$dS=rSdt+\sigma S Z \sqrt dt$  
Thus  
$(dS)^2=r^2S^2(dt)^2 + 2rS^2Zdt\sqrt dt + \sigma^2S^2Z^2dt$If we ignore dt of the order>1  
$(dS)^2\approx \sigma^2S^2Z^2dt$  
$E[Z^2]=1$ as Z is a SNV  
$(dS)^2\approx \sigma^2S^2dt$  
Thus  
$dV-\Delta dS\approx \Theta dt + \frac{\sigma^2S^2}{2}\Gamma\,dt $  
$d\Pi\approx \Theta dt + \frac{\sigma^2S^2}{2}\Gamma\,dt\qquad \Pi$ being the Delta Neutral portfolio  
If we assume the $\Pi$ grows at the rate of risk free rate $r$  

$d\Pi=r\Pi dt\approx\Theta dt + \frac{\sigma^2S^2}{2}\Gamma\,dt$  

Finally  
<div style="border:dotted;text-align:center">$r\Pi\approx\Theta  + \frac{\sigma^2S^2}{2}\Gamma$</div>




### Black Scholes Approximations
For ATM Call Options with r=q=0  
$C=SN(d_1)-S(N(d_2))$  
$d_1=\frac{\sigma\sqrt T}{2}\quad$and  
$d_1=-\frac{\sigma\sqrt T}{2}\quad$and  

$C=SN(\frac{\sigma\sqrt T}{2})-SN(-\frac{\sigma\sqrt T}{2})$  
$C=SN(\frac{\sigma\sqrt T}{2})-S(1-N(\frac{\sigma\sqrt T}{2}))$  
$C=2S(N(\frac{\sigma\sqrt T}{2})-\frac{1}{2})$  

Now let's calculate $N(\frac{\sigma^2\sqrt T}{2})$  

$N(x)=N(0)+x*N'(0)+\frac{x^2}{2}N''(0) + O(x^3)$  
$N(t)=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^te^{-\frac{x^2}{2}}\,dx$   
$N'(t)=\frac{e^{-\frac{t^2}{2}}}{\sqrt{2\pi}}$   
$N''(t)=-\frac{te^{-\frac{t^2}{2}}}{\sqrt{2\pi}}$   
$N(0)=\frac{1}{2}$  
$N'(0)=\frac{1}{\sqrt{2\pi}}$  
$N''(0)=0$   
$N(x) =  \frac{1}{2} + \frac{x}{\sqrt{2\pi}} + O(x^3) \approx \frac{1}{2} + \frac{x}{\sqrt{2\pi}}$  

$C=2S(\frac{1}{2} + \frac{\sigma\sqrt T}{2\sqrt{2\pi}})-\frac{1}{2})$  

$C=\sigma S{\sqrt\frac{T}{2\pi}}\qquad_{given\,\, r=q=0\,\, \&\,\, K=S_0\,\,N(d_1)\,\approx O(x^3)\, vis-a-vis\, Taylor}$  

**Calculating Implied Vols**  
From the above you can see that if $r=q=0$ and $K=S_0$  
##### $\sigma_{imp}=\frac{C}{S}\sqrt\frac{2\pi}{T}$  
Where $r\neq0\, and \,q\neq0$  

$C=Se^{-qT}N(\frac{(r-q)\sqrt T}{\sigma} + \frac{\sigma\sqrt T}{2})-Se^{-rT}N(\frac{(r-q)\sqrt T}{\sigma} - \frac{\sigma\sqrt T}{2})$  
By using Taylor approx. $N(x)=\frac{1}{2}+\frac{x}{\sqrt{2\pi}}$  
$C=Se^{-qT}\left(\frac{1}{2}+\frac{(r-q)\sqrt T}{\sigma\sqrt{2\pi}} + \frac{\sigma\sqrt T}{2\sqrt{2\pi}}\right)-Se^{-rT}\left(\frac{1}{2}+\frac{(r-q)\sqrt T}{\sigma\sqrt{2\pi}} + \frac{\sigma\sqrt T}{2\sqrt{2\pi}}\right)$  
$C=S(e^{-qT}-e^{-rT})\left(\frac{1}{2}+\frac{(r-q)\sqrt T}{\sigma\sqrt{2\pi}}\right)+S(e^{-qT}+e^{-rT})\left(\frac{\sigma\sqrt T}{2\sqrt{2\pi}}\right)$  
Using Taylor expansion for $e^x=1+x+\frac{x^2}{2!}$  
$e^{-qT}-e^{-rT}=(r-q)T+\frac{q^2T^2-r^2T^2}{2}$  
$e^{-qT}+e^{-rT}=1-qT+q^2T^2/2+1-rT+r^2T^2/2=2-(r+q)T+\frac{(r^2+q^2)T^2}{2}$  
Ignoring the quadratic terms of r/q  
$C=S(r-q)T\left(\frac{1}{2}+\frac{(r-q)\sqrt T}{\sigma\sqrt{2\pi}}\right)+S(2-(r+q)T)\left(\frac{\sigma\sqrt T}{2\sqrt{2\pi}}\right)$  
$C=S\frac{(r-q)T}{2}+\sigma S\left(1-\frac{(r+q)T}{2}\right)\sqrt\frac{T}{2\pi}$  
$\sigma_{imp}=\frac{\sqrt{2\pi}}{S\sqrt T}\frac{C-\frac{(r-q)T}{2}S}{1-\frac{(r+q)T}{2}}$   
##### $\sigma_{imp}=\frac{C}{S}\sqrt\frac{2\pi}{T}\frac{1-\frac{(r-q)T}{2}\frac{S}{C}}{1-\frac{(r+q)T}{2}}$   


### Black Scholes PDE from first principals

Consider a any portfolio V of a combination of underlying S and it's derivatives.  

From Taylor's series approximation you get.  

$V(S+dS,t+dt)= V(S,t) +dS\frac{\delta V}{\delta S} + dt\frac{\delta V}{\delta t} + \frac{(dS)^2}{2}\frac{\delta^2V}{\delta S^2} +O({(dt)^{(1+)}})$  

If Risk free rate is r then any asset's return is known by definition of r as below:-

$r=\frac{dS}{Sdt}$  
Thus $\frac{dS}{dt}=rS$  
$dS=rSdt$  

For a log normal of underlying asset price actually means  
$\frac{S_t}{S_{t-1}}=logN(\mu,\sigma^2)$  
$S_t=logN(log(S_{t-1})+\mu,\sigma^2)$  

$\frac{S_t}{S_{t-1}}= e^{\mu+\sigma Z}$ Where Z is a SNV.  
$S_t=S_{t-1}e^{\mu+\sigma Z}$   
$S_t=e^{log(S_{t-1})}e^{\mu+\sigma Z}$  
$S_t=e^{log(S_{t-1})+\mu+\sigma Z}$  
$S_t=e^{log(S_{t-1})+\mu+\sigma Z}$  
$S_t=e^{X}$  
$X=log(S_{t-1})+\mu+\sigma Z$  
$\frac{X-(log(S_{t-1})+\mu)}{\sigma}= Z$  
Thus $S_t=logN[log(S_{t-1})+\mu,\sigma^2]$  


Also 
$\frac{S_t}{S_{t-1}}=logN(\mu,\sigma^2)$  
$log(\frac{S_t}{S_{t-1}})=N(\mu,\sigma^2)$  
$log(\frac{S_{t-1}+dS}{S_{t-1}})=N(\mu,\sigma^2)$  
$log(1+\frac{dS}{S_{t-1}})=N(\mu,\sigma^2)$  
$\frac{dS}{S_{t-1}}=N(\mu,\sigma^2)$  
$dS=S_{t-1}N(\mu,\sigma^2)$  
$dS=S*N(\mu,\sigma^2)$  
$dS=N(\mu S,\sigma^2S^2)$  
$E(dS)=\mu S$  
$E((dS)^2)=\mu^2 S^2+\sigma^2S^2$  
$E((dS)^2)=(\mu^2+\sigma^2)S^2$  
When $\mu<<\sigma$ then  
$(dS)^2=\sigma^2S^2 dt$  
**This is not the anology that should be used here!**

It is the fact that Stock prices are log normal and that $log(S_t/S_0)=N(r,\frac{\sigma^2}{t})$  

$dS=rSdt+\sigma SZ\sqrt{dt}$  
$(dS)^2=r^2S^2(dt)^2 +\sigma^2S^2Z^2dt + 2rS^2Z(dt)^\frac{3}{2}$  
$(dS)^2\approx\sigma^2S^2Z^2dt$  
$E[(dS)^2]=E[\sigma^2S^2Z^2dt]$  
$E[(dS)^2]=\sigma^2S^2dtE[Z^2]$  
$(dS)^2=\sigma^2S^2dt$  



$V(S+dS,t+dt)= V(S,t) +dS\frac{\delta V}{\delta S} + dt\frac{\delta V}{\delta t} + \frac{(dS)^2}{2}\frac{\delta^2V}{\delta S^2} +O({(dt)^{(1+)}})$  

$V(S+dS,t+dt)= V(S,t) +dS\frac{\delta V}{\delta S} + dt\frac{\delta V}{\delta t} + \frac{\sigma^2S^2 dt}{2}\frac{\delta^2V}{\delta S^2}$  
The aim here is to define the ODE on time thus eliminate all $dS$ and define in terms of $dt$:-  
This 
$dS=(r-q)Sdt\\
dV=rVDt$  
$rVdt=  (r-q)\Delta Sdt + dt\frac{\delta V}{\delta t} + \frac{\sigma^2S^2 dt}{2}\frac{\delta^2V}{\delta S^2}$  
Thus the final ODE is  
$ (r-q)\Delta S -rV+ \frac{\delta V}{\delta t} + \frac{\sigma^2S^2}{2}\frac{\delta^2V}{\delta S^2}=0$  
$ \frac{\delta V}{\delta t} + \frac{\sigma^2S^2}{2}\Gamma+(r-q)\Delta S -rV  =0$  
--
Now making S marginally unchanged but conditional change $dS=(r-q)Sdt$ on $dt$:  
$V(S+dS,t+dt)$ becomes $V(S,t+dt)-V(S,t)=dV=rVdt$  
$dV=dS\frac{\delta V}{\delta S} + \frac{\delta V}{\delta t}dt + \frac{\sigma^2S^2 dt}{2}\frac{\delta^2V}{\delta S}$  
$rVdt=(r-q)\Delta Sdt + \Theta dt + \frac{\sigma^2S^2}{2}\Gamma dt$  

$dS=rSdt$  

$rV=(r-q)\Delta S + \Theta  + \frac{\sigma^2S^2}{2}\Gamma$  
$\Theta= rV-(r-q)\Delta S - \frac{\sigma^2S^2}{2}\Gamma$  
$\frac{dV}{dt}= rV-(r-q)\Delta S - \frac{\sigma^2S^2}{2}\Gamma\,$We are not using $\delta$ here because the assumption here is that S is marginally constant.  
$dV= r(V-\Delta S)dt+q\Delta Sdt - \frac{\sigma^2S^2}{2}\Gamma dt\,$


Solving ODE:  
$3x^2y"(x)-xy'(x)+y(x)=0\,\,\,\forall\, x\,\epsilon\,[0,1]$  
$y(0)=1$ and $y(1)=\frac{1}{2}$  

$y_n^"=\frac{y_{n+1}-2y_n+y_{n-1}}{h^2}$  
  
$y_n^\prime=\frac{y_{n+1}-y_{n-1}}{2h}$  
  
$3x_n^2\frac{y_{n+1}-2y_n+y_{n-1}}{h^2}-x_n\frac{y_{n+1}-y_{n-1}}{2h}+y_n=0$  
  
$6x_n^2h(y_{n+1}-2y_n+y_{n-1})-x_nh(y_{n+1}-y_{n-1})+y_n=0$  
  
$6x_n^2hy_{n+1}-12x_n^2hy_n+6x_n^2hy_{n-1}-x_nhy_{n+1}+x_nhy_{n-1}+y_n=0$  
  
$(6x_n^2h-x_nh)y_{n+1}    +(1-12x_n^2h)y_n      +(6x_n^2h+x_nh)y_{n-1}                   =0$  
  
$x_n=a_0+h*n$  
$x_n=0+h*n=hn$  

$(6(hn)^2h-h^2n)y_{n+1}    +(1-12(hn)^2h)y_n      +(6(hn)^2h+h^2n)y_{n-1}                   =0$  
  
$(6h^3n^2-h^2n)y_{n+1}    +(1-12h^3n^2)y_n      +(6h^3n^2+h^2n)y_{n-1}                   =0$  
  
$(6hn+1)h^2ny_{n-1}+(1-12h^3n^2)y_n+(6hn-1)h^2ny_{n+1}                             =0$  
For n=1  
$(1-12h^3n^2)y_1+(6hn-1)h^2ny_2                             =-(6hn+1)h^2ny_0$  
$(1-12h^3)y_1+(6h-1)h^2y_2                             =-(6h+1)h^2y_0$  
$(1-12h^3)y_1+(6h-1)h^2y_2                             =-(6h+1)h^2*1$  
For n=n-1  
$(6h(n-1)+1)h^2(n-1)y_{n-2}+(1-12h^3(n-1)^2)y_{n-1}                             =-(6h(n-1)-1)h^2(n-1)y_n$  
$(6h(n-1)+1)h^2(n-1)y_{n-2}+(1-12h^3(n-1)n^2)y_{n-1}                             =-(6h(n-1)-1)h^2(n-1)*\frac{1}{2}$  

In [2]:
import numpy as np

n=6                        #Number of partitions to calculate y on
h=n/6.                     #Width of each partition
A=np.full((n-1,n-1),0.)    #Linear System of n-1 by n-1 size
b=np.full(n-1,0.)          #n-1 results of the n-1 relationships
b[0]=-(6*h+1)*h**2*1                     #represents y(0)=1
b[-1]=-(6*h*(n-1)-1)*h**2*(n-1)*0.5                  #represents y(1)=1/2
for i in range(1,n):
    if i-1>0:
        A[i-1,i-2]=(6*h*i+1)*h**2*i #Coefficient of y(n-1)
    
    A[i-1,i-1]=1-12*h**3*i**2       #Coefficient of y(n)

    if i<n-1:
        A[i-1,i]=(6*h*i-1)*h**2*i #Coefficient of y(n+1)
print(A)
print(b)
print(np.matmul(np.linalg.inv(A),b))

[[ -11.    5.    0.    0.    0.]
 [  26.  -47.   22.    0.    0.]
 [   0.   57. -107.   51.    0.]
 [   0.    0.  100. -191.   92.]
 [   0.    0.    0.  155. -299.]]
[ -7.    0.    0.    0.  -72.5]
[1.12623114 1.0777085  0.97137682 0.83348893 0.67455112]


9) Consider a six months plain vanilla European call option with strike 18 on a non-dividend-paying underlying asset with spot price 20. Assume that the asset has lognormal distribution with volatility 20% and that interest rates are constant at 5%.  
(i) Compute the Greeks of the call option, i.e, $\Delta, \, \Gamma,\, \rho,\, vega\,\,\, and\,\,\, \Theta$.  
Use finite differences to find approximate values for the Greeks.  
Denote by C(S, K, T, $\sigma$, r) the value of the call option obtained from the Black-Scholes formula.

In [3]:
from scipy.stats import norm
import math
K=18
S=20
v=0.2
r=0.05
T=0.5
d1=lambda S,K,r,v,T:(math.log(S/K)+(r+v**2/2)*0.5)/v/T**0.5
d2=lambda S,K,r,v,T:(math.log(S/K)+(r-v**2/2)*0.5)/v/T**0.5
C=lambda S,K,r,v,T:S*norm.cdf(d1(S,K,r,v,T))-K*math.exp(-r*T)*norm.cdf(d2(S,K,r,v,T))
CV=C(S,K,r,v,T)
delta=(C(S+0.01*S,K,r,v,T)-CV)/0.01/S
gamma=(C(S+0.01*S,K,r,v,T)-2*CV+C(S-0.01*S,K,r,v,T))/0.01**2/S**2
rho=(C(S,K,r+0.01*r,v,T)-CV)/0.01/r
vega=(C(S,K,r,v+0.001,T)-CV)/0.001
theta=(CV-C(S,K,r,v,T-0.01*T))/0.01/T
print("Delta={:.4f}".format(delta))
print("Gamma={:.4f}".format(gamma))
print("Rho={:.4f}".format(rho))
print("Vega={:.4f}".format(vega))
print("Theta={:.4f}".format(theta))

#BSDelta
bsdelta=norm.cdf(d1(S,K,r,v,T))
print("BS Delta={:.4f}".format(bsdelta))
#Gamma
#1/v/sqrt(T)/S
bsgamma=math.exp(-d1(S,K,r,v,T)**2/2)/v/S/(2*math.pi*T)**0.5
print("BS Gamma={:.4f}".format(bsgamma))
bsrho=K*T*math.exp(-r*T)*norm.cdf(d2(S,K,r,v,T))
print("BS Rho={:.4f}".format(bsrho))
bsvega=S*T**0.5/(2*math.pi)**0.5*math.exp(-d1(S,K,r,v,T)**2/2)
print("BS Vega={:.4f}".format(bsvega))
bstheta=S*v/2/(2*math.pi*T)**0.5*math.exp(-d1(S,K,r,v,T)**2/2.) + r*K*math.exp(-r*T)*norm.cdf(d2(S,K,r,v,T))
print("BS Theta={:.4f}".format(bstheta))

Delta=0.8479
Gamma=0.0862
Rho=7.0466
Vega=3.4549
Theta=0.0154
BS Delta=0.8395
BS Gamma=0.0862
BS Rho=7.0454
BS Vega=3.4477
BS Theta=1.3941
